routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes([
    //'register' => false,
    'verify' => false
]);

/*
|------------------------------------------------------------------------------------
| Beneficiário
|------------------------------------------------------------------------------------
*/
Route::namespace('Beneficiario')->group( function () {
    Route::resource('beneficiario', 'BeneficiarioController')->except(['show']);
    Route::post('/painel', 'BeneficiarioController@logar');
    Route::get('/beneficiario/dependentes/{id}', 'BeneficiarioController@dependentes')->name('painel');
});

/*
|------------------------------------------------------------------------------------
| Questão
|------------------------------------------------------------------------------------
*/
Route::namespace('Questao')->group( function () {
    Route::resource('questao', 'QuestaoController')->except(['show']);
});


Route::get('/home', 'HomeController@index');

app/Models/Beneficiario/Beneficiario.php
<?php

namespace App\Models\Beneficiario;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class Beneficiario extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'QBeneficiario';

    protected $primaryKey = 'fk_idCliente';

    protected $fillable = [
        'fk_idCliente',
        'fk_idGrupo',
        'fk_idGrupoOperadora',
        'fk_idBeneficiario' ,
        'idOperadora' ,
        'idOperadoraApolice',
        'idOperadoraEmpresa',
        'idMatricula' ,
        'idMatriculaTitular',
        'idMatriculaEmpresa',
        'idParentesco',
        'idSexo' ,
        'idEstadoCivil' ,
        'idCorPele',
        'idIMC' ,
        'Nome' ,
        'NomeTitular',
        'CPF' ,
        'CPFTitular',
        'dtNascimento',
        'Peso' ,
        'Altura' ,
        'IMC' ,
        'eMail',
        'Telefone',
        'dtCadastro',
        'dtAtualizacao',
        'autenticado',
        'Senha'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'Senha'
    ];
}

app/Http/Controllers/Beneficiario/BeneficiarioController.php
<?php

namespace App\Http\Controllers\Beneficiario;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Beneficiario\Beneficiario;
use Illuminate\Support\Facades\Hash;
use Session;

class BeneficiarioController extends Controller
{
    public function __construct()
    {
        $this->middleware('autenticado:1');
    }

    public function index()
    {
        return view('beneficiario.login');
    }

    public function logar(Request $request){
        $data = $request->validate([
            'cpf' => 'required|string|max:20',
            'senha' => 'required|string'
        ]);
        
        $b = Beneficiario::where('CPF', $data['cpf'])->where('Senha', $data['senha'])->first();
        
        // dd($beneficiario);
        if($b){
            Session::push('id', $b->id);
            return redirect('/beneficiario/dependentes/'.$b->id);
        } else {
            return back()->with('error', 'Beneficiário não encontrado');
        }
    }

    public function dependentes($id)
    {
        $b = Beneficiario::find($id);

        $beneficiario = Beneficiario::where('CPFTitular', $b->CPFTitular)
                ->get();
        return view('beneficiario.menu')->with([
            'beneficiario' => $beneficiario 
        ]);
    }
    
    public function create()
    {

    }

    public function store(Request $request)
    {

    }
    
    public function edit($id)
    {
 
    }

    public function update(Request $request, $id)
    {

    }
    
    public function destroy($id)
    {

    }
}

resources/views/beneficiario/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Identificação</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    {{-- <link rel="stylesheet" type="text/css" href="{{asset('asset_login/css/util.css')}}"> --}}
	<link rel="stylesheet" type="text/css" href="{{asset('css/identificacao.css')}}">
</head>
<!------ Include the above in your HEAD tag ---------->
<body>
    <div class="sidenav">
        <div class="login-main-text">
           <h2>Application<br> Login Page</h2>
           <p>Login or register from here to access.</p>
        </div>
    </div>
    <div class="main">
        <div class="col-md-6 col-sm-12">
            <div class="login-form">
                @include('parts.messages')
                <form action="{{ url('/painel') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="cpf">CPF</label>
                        <input type="text" name="cpf" id="cpf" class="form-control" placeholder="CPF">
                    </div>
                    <div class="form-group">
                        <label>Senha</label>
                        <input type="password" name="senha" class="form-control" placeholder="Senha">
                    </div>
                    <button type="submit" class="btn btn-black">Entrar</button>
                    {{-- <button type="submit" class="btn btn-secondary">Register</button> --}}
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
    <script>
        $("#cpf").keydown(function(){
            try {
                $("#cpf").unmask();
            } catch (e) {}

            var tamanho = $("#cpf").val().length;

            $("#cpf").mask("999.999.999-99");

            // ajustando foco
            var elem = this;
            setTimeout(function(){
                // mudo a posição do seletor
                elem.selectionStart = elem.selectionEnd = 10000;
            }, 0);
            // reaplico o valor para mudar o foco
            var currentValue = $(this).val();
            $(this).val('');
            $(this).val(currentValue);
        });
    </script>
</body>
</html>

resources/views/beneficiario/menu.blade.php
@extends('layouts.appbeneficiario')
@section('title') Dependentes @endsection
@section('content')
    <div class="">
        <ol class="breadcrumb">
            {{-- <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Home </a></li> --}}
            <li class="active">
                Dependentes
            </li>
        </ol>

        <div class="row">
            <div class="col-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Dependentes</h2>
                        {{-- <a class="pull-right btn btn-success" href="{{url('moleculas/create')}}">
                            Nova Molécula
                        </a>
                        <div class="clearfix"></div> --}}
                    </div>
                    <div class="x_content">
                        @include('parts.messages')

                        <table class="table table-striped data_table">
                            <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nome</th>
                                <th>CPF</th>
                                <th>Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($beneficiario as $b)
                                <tr>
                                    <td>{{$b->id}}</td>
                                    <td>{{$b->Nome}}</td>
                                    <td>{{$b->CPF}}</td>
                                    <td>
                                        <a class="btn btn-primary" href="{{ route('questao.index') }}">
                                            <i class="fa fa-edit"></i> Formulário
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection